# -*- coding: utf-8 -*-
"""Freshness classification(Anjali)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BzbQkFKRqU_2mbhmBUBYLiN6up1ndLn1
"""

import pandas as pd
df=pd.read_csv('./staticfiles/data/Freshness_classification.csv')

df.head()

import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

df = df.dropna()

df.head()

cleanup_nums = {"freshness_level":     {"semifresh": 2, "fresh": 1 , "spoiled" : 3}}

df.replace(cleanup_nums, inplace=True)
df.head()

X = df.iloc[:,[3,4,5,6,7]].values
Y=df.iloc[:,8].values

Y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
classifier = LogisticRegression(random_state = 0, solver='lbfgs', multi_class='auto')
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

def predict_freshness():
    cm = confusion_matrix(y_test, y_pred)
    print(cm)

def cross_val():
    score =accuracy_score(y_test,y_pred)
    scores = cross_val_score(classifier, X_train, y_train, cv=10)
    print('Cross-Validation Accuracy Scores', scores)
    return scores

