# Generated by Django 3.0.8 on 2020-12-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('item', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temp', models.DecimalField(decimal_places=0, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('co2', models.CharField(max_length=20)),
                ('o2', models.CharField(max_length=10)),
                ('freshlevel', models.CharField(max_length=20)),
            ],
        ),
    ]
