# Generated by Django 3.0.8 on 2020-12-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='freshlevel',
            field=models.CharField(max_length=10),
        ),
    ]
