# Generated by Django 3.0.8 on 2020-12-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='humidity',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='item_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='temp',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
