# Generated by Django 3.0.8 on 2020-12-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshness', '0002_auto_20201208_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='humidity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='item',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='item_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='temp',
            field=models.CharField(max_length=20),
        ),
    ]
